### ISSUE TITLE
Base Darcula off of standard JavaFX style classes

### ISSUE THREAD

**Issue by ghost** [mousesrc/JavaFXDarculaTheme#1]
JavaFX components have style classes that ascribe to the Modena theme:

https://github.com/openjdk/jfx/blob/master/modules/javafx.controls/src/main/resources/com/sun/javafx/scene/control/skin/modena/modena.css

What do you think of updating Darcula to update the standard class names and values that are applied to components by default? For example, Modena Dark sets `-fx-base`, `-fx-background`, `-fx-accent`, and so forth:

https://github.com/joffrey-bion/javafx-themes/blob/master/css/modena_dark.css

This would allow the Darcula CSS theme to work across more applications.

**Comment by mouse0w0** [comment]
It looks good, but I cannot leave to do this recently. You could help to maintain this repository if you want.

**Comment by mouse0w0** [comment]
Now it can work.
